### ISSUE TITLE
Undefined values for Roborock E2

### ISSUE THREAD

**Issue by Kevinho195** [poketcalulator/MMM-XiaomiVacuum#1]
Thanks for your module! But my module does only show undefined values. PM2 logs doesnt show any error logs for this module.

My config:

`{
			module: 'MMM-XiaomiVacuum',
			position: 'top_right',
			header: 'Robby', // Optional
			config: {
				token: 'xxxxef69eeb316d0bfddf0b0xxxxxxxx',
				ipAddress: '192.168.xxx.xx'
				}
		},   `

![image](https://user-images.githubusercontent.com/58659198/71326469-7cf45500-24fb-11ea-91af-074a4a3e37a3.png)

**Comment by poketcalulator** [comment]
The module is built around the Xiaomi Roborock S50, and may work on previous models of the Xiaomi Roborock. According to the API from (Andreas Holstenson / aholstenson miIO Device Library) on which the module is based, I don't think it will work on the E2 model unfortunately.
