### ISSUE TITLE
Charger Offline message after restoring from backup

### ISSUE THREAD

**Issue by Milkshake665** [poketcalulator/MMM-XiaomiVacuum#2]
Hi,
First of all, thank you for this awesome contribution.

I have two roborock s5 cleaners, so I have added the module twice in config.js, but of course with each robots own unique token and IP. 

{
                        module: 'MMM-XiaomiVacuum',
                        position: 'top_right',
                        header: 'Robert', // Optional
                        config: {
                                token: '6858626a67445073344a3539307XXXXX',
                                ipAddress: '192.168.1.XXX'
                                }
                },
                {
                        module: 'MMM-XiaomiVacuum',
                        position: 'top_right',
                        header: 'Gunnar', // Optional
                        config: {
                                token: '644337376a31474562504f37647XXXXX',
                                ipAddress: '192.168.1.XXX'
                                }
                },

Issue no 1: The data for both seem to be always exactly the same, as if the data only comes from one of the units.

Issue no 2: After restoring from backup, its reads "Charger Offline". Why would that be?

Best regards
MilkShake

**Comment by poketcalulator** [comment]
Issue no 1: 
The module is not coded so it can support several simultaneous robotic vacuum cleaners. In its current form, only 1 robot vacuum cleaner is possible.

Issue no 2: 
I don't quite understand what you mean here?

**Comment by Milkshake665** [comment]
> Issue no 1:
> The module is not coded so it can support several simultaneous robotic vacuum cleaners. In its current form, only 1 robot vacuum cleaner is possible.
> 
> Issue no 2:
> I don't quite understand what you mean here?

Hi Poketcalulator,
Issue no 1: Ok, makes sense that the code does not account for multiple robots. Would be nice though. Have any idea as to get that working? Is it mentioned in the documentation?

Issue no 2: I regret the vague description. I restored my PI 4b, running latest rasbian buster, from a backup and for a time thereafter (multiple days) the app said Charger Offline. Now it works again without me doing anything.
