### ISSUE TITLE
Suddenly connection lost

### ISSUE THREAD

**Issue by iwashere13** [poketcalulator/MMM-XiaomiVacuum#3]
Hi, 

Suddenly the module has lost the connection to my xiaomi vacuum v1. Before everything was working fine. I have just updated another module (if this may have caused any strange situation I do not know).

Can you please give me a hint, how I can start bugfixing? On screen I only see "Loading...".
In Dev mode I cannot see any issue. MMM-XiaomiVacuum just receives regular module notifications as shown below.

The IP adress is still the same as in config and about the token I have no idea. I did not do any updates on my phone or vacuum.

I would like to find the root cause of this uncommon behaviour.

Thank you!

```
Load script: modules/MMM-XiaomiVacuum//MMM-XiaomiVacuum.js
module.js:468 Check MagicMirror version for module 'MMM-XiaomiVacuum' - Minimum version:  2.1.0 - Current version: 2.9.0
module.js:476 Module registered: MMM-XiaomiVacuum
loader.js:150 Bootstrapping module: MMM-XiaomiVacuum
loader.js:155 Scripts loaded for: MMM-XiaomiVacuum
loader.js:194 Load stylesheet: modules/MMM-XiaomiVacuum/MMM-XiaomiVacuum.css
loader.js:157 Styles loaded for: MMM-XiaomiVacuum
translator.js:175 MMM-XiaomiVacuum - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-XiaomiVacuum
MMM-XiaomiVacuum.js:27 Starting module: MMM-XiaomiVacuum
module.js:156 MMM-XiaomiVacuum received a system notification: ALL_MODULES_STARTED
module.js:156 MMM-XiaomiVacuum received a system notification: MODULE_DOM_CREATED
module.js:156 MMM-XiaomiVacuum received a system notification: DOM_OBJECTS_CREATED
module.js:154 MMM-XiaomiVacuum received a module notification: CLOCK_SECOND from sender: clock
module.js:154 MMM-XiaomiVacuum received a module notification: CURRENTWEATHER_DATA from sender: currentweather
module.js:154 MMM-XiaomiVacuum received a module notification: CLOCK_SECOND from sender: clock
2module.js:154 MMM-XiaomiVacuum received a module notification: CALENDAR_EVENTS from sender: calendar
module.js:154 MMM-XiaomiVacuum received a module notification: CLOCK_SECOND from sender: clock
module.js:154 
```

**Comment by poketcalulator** [comment]
If you have had my MMM-XiaomiVacuum module working, I think you should verify that the token is still correct. Furthermore, I would probably only try to load MMM-XiaomiVacuum when testing.
Optionally delete MMM-XiaomiVacuum module, reinstall this again.

Thank you for your interest in my module
