### ISSUE TITLE
Grammar issue :)

### ISSUE THREAD

**Issue by Milkshake665** [poketcalulator/MMM-XiaomiVacuum#4]
In the module it states "Reamin" and then whatever remaining percentage. Shouldn't it be "Remain"?

Anyway I changed that myself.

**Comment by poketcalulator** [comment]
Pinligt ¯\_(ツ)_/¯ 
Tak for at du har gjort mig opmærksom på det.
Jeg har fortaget rettelse dags dato, samt en lille retteles for firmware app updates.

tak for din intresse i mit modul

**Comment by poketcalulator** [comment]
Embarrassing ¯ \ _ (ツ) _ / ¯
Thanks for letting me know.
I've done the fix today, as well as a small fix for firmware app updates.

thank you for your interest in my module
